### ISSUE TITLE
Realtime Pair Ticker

### ISSUE THREAD

**Issue by D4niFPV** [andre77/bittrex-ws-java#2]
This might be an obvious question but is there a way to print to console (println) every time there's an update to a pair's price?

I've tried adding this inside the orderbook method:
> connection.received(jsons -> {
            System.out.println("MESSAGE RECEIVED: " + jsons);
        });
>
But it will only print once. Seems the connection is still open, but no more messages are received?

**Comment by andre77** [comment]
there is a subscription for "updateExchangeState" events, where objects of type [bittrex.UpdateExchangeStateItem](https://github.com/andre77/bittrex-ws-java/blob/master/src/main/java/bittrex/UpdateExchangeStateItem.java) are processed, see the [code](https://github.com/andre77/bittrex-ws-java/blob/master/src/main/java/bittrex/BittrexWS.java#L86) the object bittrex.UpdateExchangeStateItem contains the "fills" array of type [bittrex.FillUpdate](https://github.com/andre77/bittrex-ws-java/blob/master/src/main/java/bittrex/FillUpdate.java)

so you can process the "fills", where you get the last trades and last rates accordingly

have deeper look into the provided code base, everything is there, you need

**Comment by D4niFPV** [comment]
Thank you so much! I am looking into this right now.

Could you provide an example?

**Comment by xorinzor** [comment]
@CryptoTropico did you figure this out? Having the same question

EDIT: I'm running into the issue that I can't clear the existing data from the stream, so basically the stream container will continue to grow and contain more and more redundant data :/

What's the proper way of doing the idea as @andre77 points out? Because without clearing it, I have no idea. Closing and reconnecting the socket defeats the idea of using a socket.

**Comment by D4niFPV** [comment]
@xorinzor No, not yet. An example from @andre77  would be really useful!

**Comment by andre77** [comment]
sorry guys, but i do not understand, which examples you want to see...
there is already a very good one covering the most important use case: tracking the order book
just take it, use it and reduce it to your needs
everything is there, like i already said

**Comment by andre77** [comment]
@xorinzor 
> I'm running into the issue that I can't clear the existing data from the stream

what data structure do you use?
hash map, set, list?
if you add the data to your structure every time, you get an update over the websocket, sure you need some how clean it up
otherwise you end up having OME's

**Comment by xorinzor** [comment]
Basically, we want to know how to get this value: 
![screenshot 12](https://user-images.githubusercontent.com/4212335/33603294-58217082-d9b2-11e7-8b76-99a66e74a5fe.png)

I think the confusion comes from the fact that we don't really have the in-depth knowledge about how this (the orderbook, etc) all works and whats used to calculate it.

As for clearing the existing data from the stream:

`ws.getTrades(new CurrencyPair("BTC-USDT")).stream()`

That stream container just keeps growing, so I tried doing `ws.getTrades(new CurrencyPair("BTC-USDT)).clear()` at the end of the while-loop, but that has no effect at all.

**Comment by andre77** [comment]
here is an example, how you can get the last trade without changing anything
https://gist.github.com/andre77/b2b1ea6bbf2f158f342b3861247b9f08

more elegant way would be to implement s.th., where you register a listener for last trade
but for that you would need to make more changes in order to get there

@xorinzor 
>That stream container just keeps growing

sure, the getTrades methods returns the list of last trades, which is limited by 1000
see  [the code](https://github.com/andre77/bittrex-ws-java/blob/master/src/main/java/bittrex/ChannelHandler.java#L38), feel free to change the parameter in order to match your needs

i hope, it helps

**Comment by xorinzor** [comment]
@andre77 ah awesome, that is exactly what I needed, I got way too focused on that stream object.

What do you mean with implementing "s.th" ? I'd love to work with an event-based system.
Thanks for your patience.

**Comment by andre77** [comment]
@xorinzor @CryptoTropico 
just implemented the trade listener, see example [TradeListener.java](https://github.com/andre77/bittrex-ws-java/blob/master/src/main/java/TradeListener.java)

again guys, everything was there, just get it and customize it to your needs...
but since its x-mas time, little present for you ;-)

**Comment by xorinzor** [comment]
Thanks :)

**Comment by D4niFPV** [comment]
OMG @andre77 THANK YOU!!! This is what I was looking for!!!
I didn't want to bother you with this anymore, that's why I didn't ask more questions hahahah!!!

**Comment by andre77** [comment]
i guess, i can close the issue
